name: VitalSeen
version: @version@
main: com.tamrielnetwork.vitalseen.VitalSeen
api-version: 1.17
authors: [ Tamriel Network ]
website: https://tamriel.site
description: Gives players the ability to see when other players were last seen.
commands:
  vitalfly:
    description: "Main command"
    usage: "/vitalseen <player>"
permissions:
  vitalseen.seen:
    description: "Permission to see last seen date"
    default: op